server {
    listen 80;
    server_name www.vazio.club;
    return 301 https://vazio.club$request_uri;
}

server {
    listen 80;
    server_name vazio.club;
    root /usr/share/nginx/html;
    index index.html;

    location / {
        try_files $uri $uri/ =404;
    }
}
